Table config
keyboardAnt/distributed-speculative-inference pull request #42
Opened 2024-07-28 12:56 UTC by danielkorat

2024-07-28 12:59 UTC, danielkorat commented
@keyboardAnt 
Existing test fails originate from `main` (not my code)

2024-07-28 13:06 UTC, keyboardAnt commented
> @keyboardAnt 
> 
> Existing test fails originate from `main` (not my code) 

Yes, I intentionally created this skipped test to help reproduce the bug. What exception do you get there?

2024-07-28 13:08 UTC, danielkorat commented
```__________________________ ERROR at setup of test_run __________________________
file /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py, line 60
  def test_run(mock_ray, manager):
file /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py, line 53
  @pytest.fixture
  def mock_ray(mocker):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, hydra_restore_singletons, hydra_sweep_runner, hydra_task_runner, manager, mock_ray, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sample_dsi_config, sample_heatmap_config, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py:53
_________________________ ERROR at setup of test_plot __________________________
file /home/dkorat/distributed-speculative-inference/tests/unit/plot/test_plot_heatmap.py, line 40
  def test_plot(mocker, heatmap_data, plot_config):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, heatmap_data, hydra_restore_singletons, hydra_sweep_runner, hydra_task_runner, monkeypatch, plot_config, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/dkorat/distributed-speculative-inference/tests/unit/plot/test_plot_heatmap.py:40
=============================== warnings summary ===============================
tests/integration/online/test_simul.py:127
  /home/dkorat/distributed-speculative-inference/tests/integration/online/test_simul.py:127: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.timeout(90)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR tests/unit/offline/heatmap/test_manager.py::test_run
ERROR tests/unit/plot/test_plot_heatmap.py::test_plot
```

2024-07-28 20:39 UTC, keyboardAnt commented
> ```
> file /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py, line 60
>   def test_run(mock_ray, manager):
> file /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py, line 53
>   @pytest.fixture
>   def mock_ray(mocker):
> E       fixture 'mocker' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, hydra_restore_singletons, hydra_sweep_runner, hydra_task_runner, manager, mock_ray, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sample_dsi_config, sample_heatmap_config, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py:53
> _________________________ ERROR at setup of test_plot __________________________
> file /home/dkorat/distributed-speculative-inference/tests/unit/plot/test_plot_heatmap.py, line 40
>   def test_plot(mocker, heatmap_data, plot_config):
> E       fixture 'mocker' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, heatmap_data, hydra_restore_singletons, hydra_sweep_runner, hydra_task_runner, monkeypatch, plot_config, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /home/dkorat/distributed-speculative-inference/tests/unit/plot/test_plot_heatmap.py:40
> =============================== warnings summary ===============================
> tests/integration/online/test_simul.py:127
>   /home/dkorat/distributed-speculative-inference/tests/integration/online/test_simul.py:127: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
>     @pytest.mark.timeout(90)
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> =========================== short test summary info ============================
> ERROR tests/unit/offline/heatmap/test_manager.py::test_run
> ERROR tests/unit/plot/test_plot_heatmap.py::test_plot
> ```

The two tests you mentioned (`tests/unit/offline/heatmap/test_manager.py::test_run` and  `tests/unit/plot/test_plot_heatmap.py::test_plot`) are related to the heatmap, not the latency experiment. Feel free to exclude them explicitly setting the pytest path. Also, did you install all the dependencies? (`poetry install --with dev` or `poetry install --all`.) It seems like `pytest-timeout` is not installed in your environment. Please consider using the devcontainer in the future.

2024-07-28 20:40 UTC, keyboardAnt requested changes
> ```
> file /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py, line 60
>   def test_run(mock_ray, manager):
> file /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py, line 53
>   @pytest.fixture
>   def mock_ray(mocker):
> E       fixture 'mocker' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, hydra_restore_singletons, hydra_sweep_runner, hydra_task_runner, manager, mock_ray, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sample_dsi_config, sample_heatmap_config, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /home/dkorat/distributed-speculative-inference/tests/unit/offline/heatmap/test_manager.py:53
> _________________________ ERROR at setup of test_plot __________________________
> file /home/dkorat/distributed-speculative-inference/tests/unit/plot/test_plot_heatmap.py, line 40
>   def test_plot(mocker, heatmap_data, plot_config):
> E       fixture 'mocker' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, heatmap_data, hydra_restore_singletons, hydra_sweep_runner, hydra_task_runner, monkeypatch, plot_config, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /home/dkorat/distributed-speculative-inference/tests/unit/plot/test_plot_heatmap.py:40
> =============================== warnings summary ===============================
> tests/integration/online/test_simul.py:127
>   /home/dkorat/distributed-speculative-inference/tests/integration/online/test_simul.py:127: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
>     @pytest.mark.timeout(90)
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> =========================== short test summary info ============================
> ERROR tests/unit/offline/heatmap/test_manager.py::test_run
> ERROR tests/unit/plot/test_plot_heatmap.py::test_plot
> ```

The two tests you mentioned (`tests/unit/offline/heatmap/test_manager.py::test_run` and  `tests/unit/plot/test_plot_heatmap.py::test_plot`) are related to the heatmap, not the latency experiment. Feel free to exclude them explicitly setting the pytest path. Also, did you install all the dependencies? (`poetry install --with dev` or `poetry install --all`.) It seems like `pytest-timeout` is not installed in your environment. Please consider using the devcontainer in the future.

I'm converting this PR to a draft. Feel free to change when ready.

2024-07-29 07:59 UTC, danielkorat commented
Hi @keyboardAnt 
Exclude how exactly?
Please suggest changes

2024-07-30 14:00 UTC, keyboardAnt approved these changes
LGTM, please feel free to merge.

Qs:
1. What GPUs have you used?
2. Please share the results

2024-07-30 14:06 UTC, merged

2024-07-30 14:34 UTC, danielkorat commented
> LGTM, please feel free to merge.
> 
> Qs:
> 
> 1. What GPUs have you used?
> 2. Please share the results

@keyboardAnt 
1. A6000
2. I did not run a full experiment

2024-07-30 14:57 UTC, keyboardAnt commented
> > LGTM, please feel free to merge.
> 
> > 
> 
> > Qs:
> 
> > 
> 
> > 1. What GPUs have you used?
> 
> > 2. Please share the results
> 
> 
> 
> @keyboardAnt 
> 
> 1. 1 x A6000
> 
> 2. I did not run a full experiment

Can you please run a full experiment and share? Ensuring that the results are similar to the reported ones is critical.

2024-07-31 14:18 UTC, danielkorat commented
This is the output of: `python -m dsi type=table` (Note that I did not implement the table experiment myself). 
Latencies are printed in the output.
@keyboardAnt @mosheber Do you have the paper latencies for comparison?
Note that FA2 is not used below.

```
[2024-07-31 03:45:34,045][dsi.main][INFO] - type: table
simul:
  random_seed: 42
  num_repeats: 5
  c: 0.1
  a: 0.9
  k: 5
  failure_cost: 1.0
  S: 1000
  num_target_servers: 7
  c_sub: 0.01
  failure_cost_sub: 0.1
  total_tokens: 100
  wait_for_pipe: 0.1
  simul_type: DSI
  maximum_correct_tokens: 20
table:
  records:
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: lmsys/vicuna-13b-v1.3
      dataset: cnn_dailymail
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: refs/pr/5
      subset: 2.0.0
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: double7/vicuna-68m
      dataset: cnn_dailymail
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: 2.0.0
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: lmsys/vicuna-13b-v1.3
      dataset: danielkorat/alpaca
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: refs/pr/5
      subset: null
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: double7/vicuna-68m
      dataset: danielkorat/alpaca
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: null
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: lmsys/vicuna-7b-v1.3
      dataset: cnn_dailymail
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: refs/pr/4
      subset: 2.0.0
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: double7/vicuna-68m
      dataset: cnn_dailymail
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: 2.0.0
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: lmsys/vicuna-7b-v1.3
      dataset: danielkorat/alpaca
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: refs/pr/4
      subset: null
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: double7/vicuna-68m
      dataset: danielkorat/alpaca
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: null
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: bigcode/starcoder
      dataset: openai/openai_humaneval
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: refs/pr/112
      subset: null
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: bigcode/tiny_starcoder_py
      dataset: openai/openai_humaneval
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: null
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: bigcode/starcoder
      dataset: mbpp
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: refs/pr/112
      subset: null
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: bigcode/tiny_starcoder_py
      dataset: mbpp
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: null
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: microsoft/Phi-3-medium-128k-instruct
      dataset: openai/openai_humaneval
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: null
      split: test
    drafter_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: microsoft/Phi-3-mini-128k-instruct
      dataset: openai/openai_humaneval
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: null
      split: test
  - target_latency:
      random_seed: 42
      num_repeats: 5
      supported_datasets:
      - cnn_dailymail
      - danielkorat/alpaca
      - mbpp
      - openai/openai_humaneval
      model: microsoft/Phi-3-medium-128k-instruct
      dataset: mbpp
      config_gen:
        do_sample: false
        temperature: 1.0
        top_p: 1.0
      dtype: bfloat16
      num_examples: 50
      max_new_tokens: 20
      compile_model: false
      revision: null
      subset: nu [...]

2024-08-27 14:53 UTC, keyboardAnt commented
> This is the output of: `python -m dsi type=table` (Note that I did not implement the table experiment myself). Latencies are printed in the output. @keyboardAnt @mosheber Do you have the paper latencies for comparison? Note that FA2 is not used below.
> 
> ```
> [2024-07-31 06:25:11,624][dsi.main][INFO] - Running latency experiments to estimate the latency of computing a forward pass of off-the-shelf LLMs.
> [2024-07-31 06:25:11,625][dsi.main][INFO] - Running config_latency={'random_seed': 42, 'num_repeats': 5, 'supported_datasets': ['cnn_dailymail', 'danielkorat/alpaca', 'mbpp', 'openai/openai_humaneval'], 'model': 'microsoft/Phi-3-medium-128k-instruct', 'dataset': 'danielkorat/alpaca', 'config_gen': {'do_sample': False, 'temperature': 1.0, 'top_p': 1.0}, 'dtype': 'bfloat16', 'num_examples': 50, 'max_new_tokens': 20, 'compile_model': False, 'revision': None, 'subset': None, 'split': 'test'}
> [2024-07-31 06:25:11,626][dsi.online.latency.experiment][INFO] - Loading dataset: danielkorat/alpaca
> [2024-07-31 06:25:14,835][dsi.online.latency.experiment][INFO] - Loading model: microsoft/Phi-3-medium-128k-instruct, compile=False
> [2024-07-31 06:25:15,508][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
> [2024-07-31 06:25:15,508][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
> [2024-07-31 06:28:40,102][dsi.online.latency.experiment][INFO] - Loading dataset: danielkorat/alpaca
> [2024-07-31 06:28:43,303][dsi.online.latency.experiment][INFO] - Loading model: microsoft/Phi-3-medium-128k-instruct, compile=False
> [2024-07-31 06:28:43,823][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
> [2024-07-31 06:28:43,824][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
> [2024-07-31 06:32:09,100][dsi.online.latency.experiment][INFO] - Loading dataset: danielkorat/alpaca
> [2024-07-31 06:32:12,313][dsi.online.latency.experiment][INFO] - Loading model: microsoft/Phi-3-medium-128k-instruct, compile=False
> [2024-07-31 06:32:12,810][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
> [2024-07-31 06:32:12,810][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
> [2024-07-31 06:35:44,129][dsi.online.latency.experiment][INFO] - Loading dataset: danielkorat/alpaca
> [2024-07-31 06:35:47,248][dsi.online.latency.experiment][INFO] - Loading model: microsoft/Phi-3-medium-128k-instruct, compile=False
> [2024-07-31 06:35:47,773][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
> [2024-07-31 06:35:47,773][transformers_modules.microsoft.Phi-3-medium-128k-instruct.cae1d42b5577398fd1be9f0746052562ae552886.modeling_phi3][WARNING] - Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
> ```

Are the results for the last combination missing? (that is, target `microsoft/Phi-3-medium-128k-instruct`, drafter `microsoft/Phi-3-mini-128k-instruct`, dataset `danielkorat/alpaca`)